### ISSUE TITLE
[Issue / Suggestion] Does not work with 'Key remapping' -plugin

### ISSUE THREAD

**Issue by ZeiZeiii** [lightningboltemoji/clear-unsent-messages#3]
This plugin does work with 'Key remapping' -plugin. It overrides chat box with "Press Enter to Chat" which requires to press enter before typing. This also requires re-press enter to "exit" chat box. After clearing the chat box, the box is still active, so dialogue shortcuts wont work for example.

Pretty easy to fix, just make this plugin to press enter after clearing the chat box.

**Comment by lightningboltemoji** [comment]
Great suggestion! Thanks for that. 

I had to make one related behavioral decision... if you have Key Mapping enabled, press enter, and don't type anything - it'll kick you back to `Press Enter to Chat...` after the configured delay. I thought that seemed most appropriate for it to do, as opposed to showing the chat prompt indefinitely.

Will be included in the next update:
* https://github.com/runelite/plugin-hub/pull/3896
* https://github.com/lightningboltemoji/clear-unsent-messages/commit/4415a43828ac289817b73f05d8609503b3620ec7

Closing the issue for now, but feel free to reopen if you run into issues with it after the update is merged (above).
