### ISSUE TITLE
No longer working after update

### ISSUE THREAD

**Issue by UhCloudd** [lightningboltemoji/clear-unsent-messages#4]
Hello. The plugin seems to no longer be working after the most recent update that took place earlier this week. I have tried uninstalling and reinstalling it and also troubleshooted with Runelite to be sure it wasn't the culprit either.
Thanks!

**Comment by Bolarino** [comment]
Having the same issue, plugin no longer works.

**Comment by lightningboltemoji** [comment]
Thanks for reporting and +1ing, all. Sorry I missed this. Looking into it tonight.
